name: ğŸ”¥ Build Release Gradle project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# -------------------------------------------------
# 1ï¸âƒ£ CHECKOUT
# -------------------------------------------------
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥ Checkout project sources"
        uses: actions/checkout@v4

  # -------------------------------------------------
  # 2ï¸âƒ£ BUILD
  # -------------------------------------------------
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4

      - name: "â˜•ï¸ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '25'
          cache: 'gradle'

      - name: "ğŸ˜ Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: "ğŸ”’ Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "ğŸ”¨ Build with Gradle"
        run: ./gradlew installDist

  # -------------------------------------------------
  # 3ï¸âƒ£ PUBLISH
  # -------------------------------------------------
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "ğŸš€ Publish Gradle Application Artifacts"
        uses: actions/upload-artifact@v6
        with:
          name: distribution-zip
          path: |
            build/distributions/*.zip
            retention-days: 3